model:
    arch: segnet
data:
    dataset: cityscapes
    train_split: train 
    val_split: val 
    img_rows: 512
    img_cols: 1024
    path: /home/dmei/data/
training:
    n_workers: 64
    train_iters: 20000
    batch_size: 64
    val_interval: 500
    print_interval: 25
    loss:
        name: 'cross_entropy'
    optimizer:
        name: 'adam'
        lr: 1.0e-4
    lr_schedule:
        name: 'constant_lr'
    momentum: 0.99
    weight_decay: 0.0005
    visdom: False
    resume: 
