model:
    arch: segnet
data:
    dataset: cityscapes
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 1024
    path: /cs231n_finalproject/data/
training:
    train_iters: 20000
    batch_size: 64
    val_interval: 500
    print_interval: 25
    optimizer:
        lr: 1.0e-4
    l_rate: 1.0e-4
    l_schedule:
    momentum: 0.99
    weight_decay: 0.0005
    visdom: False
